In [1]:
import pandas as pd
import os
import openpyxl

In [48]:
folder_path = "D:\\_workspace\\_billing\\_FEE sources"

for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)
    print(file_path.split("\\")[-1])
    sheetname = "Packed"
    try:
        df = pd.read_excel(file_path, sheet_name=sheetname)
        print(f"Read {sheetname} with {len(df)} successfully")
    except Exception as e:
        print(f"File {filename} khong ton tai sheet {sheetname}")

20250430_FEE_030000.xlsx
Read Packed with 146092 successfully
20250430_FEE_StorageBasedOnInventory_030000.xlsx
File 20250430_FEE_StorageBasedOnInventory_030000.xlsx khong ton tai sheet Packed
20250531_FEE_030000_AAB_ACB.xlsx
Read Packed with 196646 successfully
20250531_FEE_StorageBasedOnInventory_030000.xlsx
File 20250531_FEE_StorageBasedOnInventory_030000.xlsx khong ton tai sheet Packed
20250630_FEE_030000.xlsx
Read Packed with 211758 successfully
20250630_FEE_StorageBasedOnInventory.xlsx
File 20250630_FEE_StorageBasedOnInventory.xlsx khong ton tai sheet Packed
20250731_FEE_030000.xlsx
Read Packed with 211604 successfully
20250731_FEE_StorageBasedOnInventory_030000.xlsx
File 20250731_FEE_StorageBasedOnInventory_030000.xlsx khong ton tai sheet Packed
20250831_FEE_030000.xlsx
Read Packed with 193677 successfully
20250831_FEE_StorageBasedOnInventory_030000.xlsx
File 20250831_FEE_StorageBasedOnInventory_030000.xlsx khong ton tai sheet Packed
AAD_202505.xlsx
Read Packed with 44262 successfully
AAD_202506.xlsx
Read Packed with 89968 successfully
AAD_202507.xlsx
Read Packed with 3802 successfully
AAD_202508.xlsx
Read Packed with 2106 successfully
JVM_stock.xlsx
File JVM_stock.xlsx khong ton tai sheet Packed
MSN_202505.xlsx
File MSN_202505.xlsx khong ton tai sheet Packed
MSN_202506.xlsx
File MSN_202506.xlsx khong ton tai sheet Packed
MSN_202507.xlsx
File MSN_202507.xlsx khong ton tai sheet Packed
MSN_202508.xlsx
File MSN_202508.xlsx khong ton tai sheet Packed
~$20250831_FEE_030000.xlsx
File ~$20250831_FEE_030000.xlsx khong ton tai sheet Packed

In [ ]:
folder_path = "D:\\_workspace\\_billing\\_FEE sources"

for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)
    if "MSN" in file_path:
        print(file_path)
        workbook = openpyxl.load_workbook(file_path)
        print("load workbook successfully")
        for shetname in workbook.sheetnames:
            print(shetname)


filename = "D:\\_workspace\\_billing\\_FEE sources\\MSN_202505.xlsx"
excel = pd.ExcelFile(filename)
print(excel.sheet_names)

In [ ]:
import pandas as pd
import openpyxl
import os

folder_path = "D:\\_workspace\\_billing\\_FEE sources"
chunk_size = 10000  # Read 10,000 rows at a time

# Iterate through chunks and process them
for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)
    if "MSN" in file_path:
        print(file_path)
        workbook = openpyxl.load_workbook(filename=file_path, read_only=True)
        for sheetname in workbook.sheetnames:
            print(sheetname)

In [ ]:
from datetime import datetime


def is_datetime_format(date_string, date_format):
    try:
        datetime.strptime(date_string, date_format)
        return True
    except ValueError:
        return False


# Example with a valid datetime string
string1 = "2023-10-27 15:30:00"
format1 = "%Y-%m-%d %H:%M:%S"
print(f"'{string1}' is in '{format1}' format: {is_datetime_format(string1, format1)}")

# Example with an invalid datetime string for the given format
string2 = "October 27, 2023"
format2 = "%Y-%m-%d %H:%M:%S"
print(f"'{string2}' is in '{format2}' format: {is_datetime_format(string2, format2)}")

# Example with a different valid format
string3 = "27/10/2023"
format3 = "%d/%m/%Y"
print(f"'{string3}' is in '{format3}' format: {is_datetime_format(string3, format3)}")

In [ ]:
sheet_names = [
    "Storage",
    "Receive",
    "PrepServices",
    "Packed",
    "Ship",
    "ReturnReceive_Delivered",
    "ReturnReceive_NotDelivered",
    "Picked",
    "COD",
]

column_mappings = {
    "Packed": {
        "Ngày tạo SO": "so_date",
        "Mã SO Eton": "so_number",
        "Mã SO client": "so_number_client",
        "BizType": "biztype",
        "Trạng thái SO": "so_status",
        "Ngày Pack": "packed_date",
        "Tên client": "client_name",
        "SKU": "sku",
        "Tên sản phẩm": "description",
        "LWH": "lwh",
        "L(cm)": "l_cm",
        "W(cm)": "w_cm",
        "H(cm)": "h_cm",
        "Weight": "weight_g",
        "PackedQty": "packed_qty",
        "Warehouse": "warehouse",
        "CategoryName": "category",
        "CancelledNote": "cancelled_note",
        "SO Extra Service": "so_extra_service",
        "Mã khách hàng": "client_code",
        "ShippingService": "shipping_service",
    },
    "Receive": {
        "Ngày tạo PO": "po_date",
        "Mã PO của Eton": "po_number",
        "Mã PO của Client": "po_number_client",
        "Tên kho": "warehouse",
        "Ngày hàng đến kho": "received_date",
        "Ngày nhập hàng": "inbound_date",
        "Tên Client": "client_name",
        "SKU": "sku",
        "Tên sản phẩm": "description",
        "Tên ngành hàng": "brand",
        "Nhóm": "category",
        "LWH": "lwh",
        "L(cm)": "l_cm",
        "W(cm)": "w_cm",
        "H(cm)": "h_cm",
        "Weight(g)": "weight_g",
        "Số lượng thực nhập mới": "quantity_new",
        "Số lượng thực nhập hỏng": "quantity_damaged",
        "PO status": "po_status",
        "Ngày hoàn tất nhập hàng": "completed_ib_date",
        "Giá Trị Khai Giá": "product_value",
        "Mã khách hàng": "client_code",
        "PO Extra Service": "po_extra_service",
    },
}

In [ ]:
packed_mapping = {
    "Ngày tạo SO": "so_date",
    "Mã SO Eton": "so_number",
    "Mã SO client": "so_number_client",
    "BizType": "biztype",
}

receive_mapping = {}
prepservices_mapping = {}
ship_mapping = {}
returnreceive_delivered_mapping = {}
returnreceive_notdelivered_mapping = {}
cod_mapping = {}

columns = ", ".join([v for v in packed_mapping.values()])
print(columns)

In [ ]:
from configparser import ConfigParser


def config(filename="database.ini", section="postgresql"):
    # create a parser
    parser = ConfigParser()
    # read config file
    parser.read(filename)

    # get section, default to postgresql
    db = {}
    if parser.has_section(section):
        params = parser.items(section)
        for param in params:
            db[param[0]] = param[1]
    else:
        raise Exception(
            "Section {0} not found in the {1} file".format(section, filename)
        )

    return db

In [ ]:
folder_path = "../.data"
for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)
    print(f"Filename: {filename}, Size: {os.path.getsize(file_path)} bytes")
    file = pd.read_excel(file_path)
    print(file.sheet_names)
    file.close()

In [ ]:
import psycopg2


def connect_to_postgresql():
    """Connect to PostgreSQL database and return the connection object."""
    conn = None
    try:
        conn = psycopg2.connect(
            host="localhost",
            database="wms",
            user="postgres",
            password="123456",
            port="5432",  # or your specific port
        )
        print("Connected to PostgreSQL!")

        # Further operations (creating a cursor, executing queries) would go here
        cursor = conn.cursor()
        cursor.execute("SELECT version();")
        db_version = cursor.fetchone()
        print(f"Database version: {db_version}")

    except psycopg2.Error as e:
        print(f"Error connecting to PostgreSQL: {e}")

    finally:
        # Ensure the connection is closed even if errors occur
        if conn:
            conn.close()
            print("Connection closed.")


connect_to_postgresql()

In [ ]:
import psycopg2
from psycopg2 import extras
from datetime import datetime, date


def bulk_insert_execute_batch(sql, data_list):
    conn = None
    try:
        conn = psycopg2.connect(
            host="localhost",
            database="bootcamp",
            user="postgres",
            password="123456",
            port="5432",  # or your specific port
        )
        cur = conn.cursor()

        sql = sql
        extras.execute_batch(cur, sql, data_list)
        conn.commit()
        print(f"{len(data_list)} rows inserted successfully using execute_batch.")

    except (Exception, psycopg2.Error) as error:
        print(f"Error: {error}")
    finally:
        if conn:
            cur.close()
            conn.close()

In [ ]:
# insert purchase orders

date_format = "%m-%d-%Y"
path = "..\\.data\\20250831_FEE_030000.xlsx"
data = pd.read_excel(path)
columns = ["Ngày tạo PO", "Mã PO của Eton", "Mã PO của Client", "Tên kho"]
data = data[columns]
data["Ngày tạo PO"] = pd.to_datetime(data["Ngày tạo PO"]).dt.date
# print(data.head(3))
# print(data.dtypes)
columns_insert = ["po_date", "po_number", "po_number_client", "warehouse"]
schema = "wms"
table = "receive_short"
sql = f"INSERT INTO {schema}.{table} ({', '.join(columns_insert)}) VALUES ({', '.join(['%s'] * len(columns_insert))})"
data_to_insert = [tuple(x) for x in data.to_numpy()]
# print(data_to_insert)
# data_to_insert = [tuple(x) for x in data.to_numpy()]
# Example usage (same data as above):
bulk_insert_execute_batch(sql, data_to_insert)

In [ ]:
# insert sales orders

packed_mapping = {
    "Ngày tạo SO": "so_date",
    "Mã SO Eton": "so_number",
    "Mã SO client": "so_number_client",
    "BizType": "biztype",
}

so_columns = list(packed_mapping.keys())

date_format = "%m-%d-%Y"
date_str_format = "%m/%d/%Y %I:%M:%S %p"
path = "..\\.data\\20250831_FEE_030000.xlsx"
data = pd.read_excel(path, sheet_name="Packed")
columns = ["Ngày tạo SO", "Mã SO Eton", "Mã SO client", "BizType"]
data = data[columns]
data["Ngày tạo SO"] = pd.to_datetime(
    data["Ngày tạo SO"], format=date_str_format
).dt.date
columns_insert = ["so_date", "so_number", "so_number_client", "biztype"]
schema = "wms"
table = "packed_short"
sql = f"INSERT INTO {schema}.{table} ({', '.join(columns_insert)}) VALUES ({', '.join(['%s'] * len(columns_insert))})"
data_to_insert = [tuple(x) for x in data.to_numpy()]
# Example usage (same data as above):
bulk_insert_execute_batch(sql, data_to_insert)

In [ ]:
path = "..\\.data\\20250831_FEE_030000.xlsx"
data = pd.read_excel(path, sheet_name="Packed")
data_to_insert = [tuple(x) for x in data.to_numpy()]

In [ ]:
print(data.head())

In [ ]:
print(data.to_numpy()[0])

In [34]:
path = "..\\.data\\20250831_FEE_030000.xlsx"
print(path.split("\\")[-1])

20250831_FEE_030000.xlsx

In [51]:
def extract(path: str, sheetname: str, mappings: dict) -> pd.DataFrame:
    # read excel file
    try:
        df = pd.read_excel(path, sheet_name=sheetname)

        # add column to note datasource
        filename = str(path.split("\\")[-1].strip())
        df["reference_source"] = filename

        # add new column to mappings object
        mappings["reference_source"] = "reference_source"

        # rename columns to matching with database
        df.rename(columns=mappings, inplace=True)

        return df[[col for col in mappings.values()]]

    except Exception as e:
        print(f"Fail to read {path} with sheet {sheetname}")

    return pd.DataFrame()

In [54]:
path = "..\\.data\\20250831_FEE_030000.xlsx"

packed_mapping = {
    "Ngày tạo SO": "so_date",
    "Mã SO Eton": "so_number",
    "Mã SO client": "so_number_client",
    "BizType": "biztype",
}

sheetname = "Packed"
mappings = column_mappings["Packed"]
df = extract(path, sheetname, mappings=mappings)
df.head()

,so_date,so_number,so_number_client,biztype,so_status,packed_date,client_name,sku,description,lwh,...,h_cm,weight_g,packed_qty,warehouse,category,cancelled_note,so_extra_service,client_code,shipping_service,reference_source
0,8/6/2025 8:24:44 PM,SOUNAWXGMJRZM,1000746-6825,B2C,ClientHandOn,8/7/2025 12:00:00 AM,Công ty TNHH Dịch vụ UNA,1018,Calm Water Gel - 177ml,5x5x17,...,17.0,460.0,1,Q7 FC,PROFESSIONAL,NaN,NaN,UNA,B2C Standard,20250831_FEE_030000.xlsx
1,8/4/2025 9:33:35 PM,SOUNA2CP3ZHE5,666-4825,B2C,ClientHandOn,8/5/2025 12:00:00 AM,Công ty TNHH Dịch vụ UNA,1018,Calm Water Gel - 177ml,5x5x17,...,17.0,460.0,1,Q7 FC,PROFESSIONAL,NaN,NaN,UNA,B2C Standard,20250831_FEE_030000.xlsx
2,7/31/2025 6:31:34 PM,SOUNAAXM3FMZC,25 - DID - 07170,B2C,ClientHandOn,8/1/2025 12:00:00 AM,Công ty TNHH Dịch vụ UNA,1018,Calm Water Gel - 177ml,5x5x17,...,17.0,460.0,1,Arya FC,PROFESSIONAL,NaN,NaN,UNA,B2C Standard,20250831_FEE_030000.xlsx
3,8/12/2025 6:10:48 PM,SOUNA6RSWN8YB,291-12825,B2C,ClientHandOn,8/13/2025 12:00:00 AM,Công ty TNHH Dịch vụ UNA,1018,Calm Water Gel - 177ml,5x5x17,...,17.0,460.0,1,Q7 FC,PROFESSIONAL,NaN,NaN,UNA,B2C Standard,20250831_FEE_030000.xlsx
4,8/12/2025 6:10:48 PM,SOUNACWMBDWPD,200054-12825,B2C,ClientHandOn,8/13/2025 12:00:00 AM,Công ty TNHH Dịch vụ UNA,1018,Calm Water Gel - 177ml,5x5x17,...,17.0,460.0,1,Q7 FC,PROFESSIONAL,NaN,NaN,UNA,B2C Standard,20250831_FEE_030000.xlsx

In [ ]:
def convert_datetime_to_date(
    df: pd.DataFrame, columns: list, date_format: str
) -> pd.DataFrame:
    for column in columns:
        try:
            df[column] = pd.to_datetime(df[column], format=date_format).dt.date
            print(f"Convert column {column} to date successfully")
        except:
            print(f"Fail to convert {column} from datetime to date")

    return df

Fail to convert so_number from datetime to date
Convert column packed_date to date successfully

,so_date,so_number,so_number_client,biztype,so_status,packed_date,client_name,sku,description,lwh,...,h_cm,weight_g,packed_qty,warehouse,category,cancelled_note,so_extra_service,client_code,shipping_service,reference_source
0,8/6/2025 8:24:44 PM,SOUNAWXGMJRZM,1000746-6825,B2C,ClientHandOn,2025-08-07,Công ty TNHH Dịch vụ UNA,1018,Calm Water Gel - 177ml,5x5x17,...,17.0,460.0,1,Q7 FC,PROFESSIONAL,NaN,NaN,UNA,B2C Standard,20250831_FEE_030000.xlsx
1,8/4/2025 9:33:35 PM,SOUNA2CP3ZHE5,666-4825,B2C,ClientHandOn,2025-08-05,Công ty TNHH Dịch vụ UNA,1018,Calm Water Gel - 177ml,5x5x17,...,17.0,460.0,1,Q7 FC,PROFESSIONAL,NaN,NaN,UNA,B2C Standard,20250831_FEE_030000.xlsx
2,7/31/2025 6:31:34 PM,SOUNAAXM3FMZC,25 - DID - 07170,B2C,ClientHandOn,2025-08-01,Công ty TNHH Dịch vụ UNA,1018,Calm Water Gel - 177ml,5x5x17,...,17.0,460.0,1,Arya FC,PROFESSIONAL,NaN,NaN,UNA,B2C Standard,20250831_FEE_030000.xlsx
3,8/12/2025 6:10:48 PM,SOUNA6RSWN8YB,291-12825,B2C,ClientHandOn,2025-08-13,Công ty TNHH Dịch vụ UNA,1018,Calm Water Gel - 177ml,5x5x17,...,17.0,460.0,1,Q7 FC,PROFESSIONAL,NaN,NaN,UNA,B2C Standard,20250831_FEE_030000.xlsx
4,8/12/2025 6:10:48 PM,SOUNACWMBDWPD,200054-12825,B2C,ClientHandOn,2025-08-13,Công ty TNHH Dịch vụ UNA,1018,Calm Water Gel - 177ml,5x5x17,...,17.0,460.0,1,Q7 FC,PROFESSIONAL,NaN,NaN,UNA,B2C Standard,20250831_FEE_030000.xlsx

In [ ]:
column_to_transform = ["so_number", "packed_date"]

date_str_format = "%m/%d/%Y %I:%M:%S %p"

df = convert_datetime_to_date(df, column_to_transform, date_str_format)
df.head()
# df.info()
# print(type(", ".join(df.columns)))

In [42]:
print(df.groupby("client_code")["so_number"].nunique())

client_code
AAB        4
ACB    36356
ANM     5995
AOS       84
BFB     4387
DNT       10
EVX      136
FAM     1093
ION       26
JVM      202
MSA    64459
NLV        1
NVL        2
PCH      114
PRV      224
SOC      173
SWS      174
TCV     9578
TTL      707
UNA      542
VNP     4137
VNS       33
YEU       27
Name: so_number, dtype: int64

In [ ]:
def data_loader(data: pd.DataFrame, schema, table) -> bool:
    columns_insert = list(data.columns)
    sql = f"INSERT INTO {schema}.{table} ({', '.join(columns_insert)}) VALUES ({', '.join(['%s'] * len(columns_insert))})"
    data_to_insert = [tuple(x) for x in data.to_numpy()]
    try:
        bulk_insert_execute_batch(sql, data_to_insert)
        return True
    except Exception as e:
        print(e)
    return False

193677 rows inserted successfully using execute_batch.

True

In [ ]:
schema = "wms"
table = "packed"
data_loader(df, schema, table)

In [ ]:
import dask
import dask.dataframe as dd
import pandas as pd
import os

folder_path = "D:\\_workspace\\_billing\\_FEE sources\\MSN_202508.xlsx"
chunk_size = 10000  # Read 10,000 rows at a time

# Iterate through chunks and process them
for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)
    if "MSN" in file_path:
        print(file_path)
        df = dd.from_pandas(
            pd.read_excel(file_path, sheet_name=None), npartitions=4
        )  # Adjust npartitions as needed

        print(df.head())

D:\_workspace\_billing\_FEE sources\MSN_202505.xlsx
  Ngày tạo PO Mã PO của Eton       Mã PO của Client Tên kho Ngày hàng đến kho  \
0  2025-05-10  POMSNS2RSYKCW  YYRK_13747394_6520511   Q7 FC        2025-05-12
1  2025-05-16  POMSNP3FHEIZ1  YYRK_13747394_6693783   Q7 FC        2025-05-17
2  2025-05-14  POMSNHACPVUNU          POMSNHACPVUNU   Q7 FC        2025-05-28
3  2025-05-10  POMSNB5MHPYZV  YYRK_13747394_6520495   Q7 FC        2025-05-10
4  2025-05-16  POMSNAYZEWFU6  YYRK_13747394_6693648   Q7 FC        2025-05-17

  Ngày nhập hàng                              Tên Client            SKU  \
0     2025-05-12  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789318
1     2025-05-17  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789318
2     2025-05-28  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789318
3     2025-05-10  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789318
4     2025-05-17  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789318

                                        Tên sản phẩm Tên ngành hàng  ...  \
0  COLORKEY LUMINOUS FACIAL MASK 25ml HYDRATING（越...       colorkey  ...
1  COLORKEY LUMINOUS FACIAL MASK 25ml HYDRATING（越...       colorkey  ...
2  COLORKEY LUMINOUS FACIAL MASK 25ml HYDRATING（越...       colorkey  ...
3  COLORKEY LUMINOUS FACIAL MASK 25ml HYDRATING（越...       colorkey  ...
4  COLORKEY LUMINOUS FACIAL MASK 25ml HYDRATING（越...       colorkey  ...

             Loại SKU Số Qty unit/case  Số unit/combo  Dung tích(cm3)  \
0  ProductType_Single              560              0            20.4
1  ProductType_Single              560              0            20.4
2  ProductType_Single              560              0            20.4
3  ProductType_Single              560              0            20.4
4  ProductType_Single              560              0            20.4

   Mã tham khảo của Client  Đơn vị tính  Ngày hoàn tất nhập hàng  \
0                  6520511          pcs  2025-05-13 14:07:50.270
1                  6693783          pcs  2025-05-17 10:05:20.883
2                     <NA>          pcs  2025-05-29 11:37:31.530
3                  6520495          pcs  2025-05-10 16:29:05.253
4                  6693648          pcs  2025-05-17 10:41:14.923

   Giá Trị Khai Giá Mã khách hàng PO Extra Service
0               NaN           MSN             <NA>
1               NaN           MSN             <NA>
2               NaN           MSN             <NA>
3               NaN           MSN             <NA>
4               NaN           MSN             <NA>

[5 rows x 29 columns]
D:\_workspace\_billing\_FEE sources\MSN_202506.xlsx
  Ngày tạo PO Mã PO của Eton       Mã PO của Client Tên kho Ngày hàng đến kho  \
0  2025-05-10  POMSNS2RSYKCW  YYRK_13747394_6520511   Q7 FC        2025-05-12
1  2025-05-16  POMSNP3FHEIZ1  YYRK_13747394_6693783   Q7 FC        2025-05-17
2  2025-05-14  POMSNHACPVUNU          POMSNHACPVUNU   Q7 FC        2025-05-28
3  2025-05-10  POMSNB5MHPYZV  YYRK_13747394_6520495   Q7 FC        2025-05-10
4  2025-05-16  POMSNAYZEWFU6  YYRK_13747394_6693648   Q7 FC        2025-05-17

  Ngày nhập hàng                              Tên Client            SKU  \
0     2025-05-12  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789318
1     2025-05-17  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789318
2     2025-05-28  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789318
3     2025-05-10  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789318
4     2025-05-17  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789318

                                        Tên sản phẩm Tên ngành hàng  ...  \
0  COLORKEY LUMINOUS FACIAL MASK 25ml HYDRATING（越...       colorkey  ...
1  COLORKEY LUMINOUS FACIAL MASK 25ml HYDRATING（越...       colorkey  ...
2  COLORKEY LUMINOUS FACIAL MASK 25ml HYDRATING（越...       colorkey  ...
3  COLORKEY LUMINOUS FACIAL MASK 25ml HYDRATING（越...       colorkey  ...
4  COLORKEY LUMINOUS FACIAL MASK 25ml HYDRATING（越...       colorkey  ...

             Loại SKU Số Qty unit/case  Số unit/combo  Dung tích(cm3)  \
0  ProductType_Single              560              0            20.4
1  ProductType_Single              560              0            20.4
2  ProductType_Single              560              0            20.4
3  ProductType_Single              560              0            20.4
4  ProductType_Single              560              0            20.4

   Mã tham khảo của Client  Đơn vị tính  Ngày hoàn tất nhập hàng  \
0                  6520511          pcs  2025-05-13 14:07:50.270
1                  6693783          pcs  2025-05-17 10:05:20.883
2                     <NA>          pcs  2025-05-29 11:37:31.530
3                  6520495          pcs  2025-05-10 16:29:05.253
4                  6693648          pcs  2025-05-17 10:41:14.923

   Giá Trị Khai Giá Mã khách hàng PO Extra Service
0               NaN           MSN             <NA>
1               NaN           MSN             <NA>
2               NaN           MSN             <NA>
3               NaN           MSN             <NA>
4               NaN           MSN             <NA>

[5 rows x 29 columns]
D:\_workspace\_billing\_FEE sources\MSN_202507.xlsx
  Ngày tạo PO Mã PO của Eton Mã PO của Client Tên kho Ngày hàng đến kho  \
0  2025-07-18  POMSNJIGKBIJX       1480885287   Q7 FC        2025-07-25
1  2025-07-13  POMSNDAIKCGYE       1480872707   Q7 FC        2025-07-19
2  2025-05-19  POMSNTY1UC4RW       1480720053   Q7 FC        2025-07-08
3  2025-07-18  POMSNYIGWVWMW       1480885036   Q7 FC        2025-07-25
4  2025-06-06  POMSNQIPREGR4       1480766093   Q7 FC        2025-07-07

  Ngày nhập hàng                              Tên Client            SKU  \
0     2025-07-25  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789929
1     2025-07-19  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789929
2     2025-07-08  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789929
3     2025-07-25  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789929
4     2025-07-07  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326789929

                                        Tên sản phẩm Tên ngành hàng  ...  \
0  COLORKEY Lasting Naturally-occurring Loose Pow...       colorkey  ...
1  COLORKEY Lasting Naturally-occurring Loose Pow...       colorkey  ...
2  COLORKEY Lasting Naturally-occurring Loose Pow...       colorkey  ...
3  COLORKEY Lasting Naturally-occurring Loose Pow...       colorkey  ...
4  COLORKEY Lasting Naturally-occurring Loose Pow...       colorkey  ...

             Loại SKU Số Qty unit/case  Số unit/combo  Dung tích(cm3)  \
0  ProductType_Single               96              0           224.0
1  ProductType_Single               96              0           224.0
2  ProductType_Single               96              0           224.0
3  ProductType_Single               96              0           224.0
4  ProductType_Single               96              0           224.0

   Mã tham khảo của Client  Đơn vị tính  Ngày hoàn tất nhập hàng  \
0       579613160902592102          pcs  2025-07-25 13:33:08.543
1       579539630934164492          pcs  2025-07-19 16:03:07.710
2       578809443552495602          pcs  2025-07-08 10:17:36.507
3       579597397297301140          pcs  2025-07-25 13:24:39.603
4       579101400242357278          pcs  2025-07-07 15:06:30.190

   Giá Trị Khai Giá Mã khách hàng PO Extra Service
0               NaN           MSN             <NA>
1               NaN           MSN             <NA>
2               NaN           MSN             <NA>
3               NaN           MSN             <NA>
4               NaN           MSN             <NA>

[5 rows x 29 columns]
D:\_workspace\_billing\_FEE sources\MSN_202508.xlsx
  Ngày tạo PO Mã PO của Eton Mã PO của Client Tên kho Ngày hàng đến kho  \
0  2025-08-07  POMSNPBEMRSER       1480939720   Q7 FC        2025-08-20
1  2025-07-27  POMSNXGMKZTNA       1480908457   Q7 FC        2025-08-05
2  2025-08-14  POMSNAUNRRIMC       1480932935   Q7 FC        2025-08-15
3  2025-08-14  POMSNW3QDGVWT       1480958547   Q7 FC        2025-08-15
4  2025-08-11  POMSN2QBSHAES       1480951673   Q7 FC        2025-08-30

  Ngày nhập hàng                              Tên Client            SKU  \
0     2025-08-20  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6971942356118
1     2025-08-05  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6971942356118
2     2025-08-15  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326787680
3     2025-08-15  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326787680
4     2025-08-30  CÔNG TY TNHH MỸ PHẨM MEISHANG VIỆT NAM  6975326787680

                                 Tên sản phẩm Tên ngành hàng  ...  \
0      COLORKEY ROSÉ Rosé Crush EAU DE PARFUM       colorkey  ...
1      COLORKEY ROSÉ Rosé Crush EAU DE PARFUM       colorkey  ...
2  COLORKEY LUMINOUS MOISTURE GEL 15ml（越南版乳霜）       colorkey  ...
3  COLORKEY LUMINOUS MOISTURE GEL 15ml（越南版乳霜）       colorkey  ...
4  COLORKEY LUMINOUS MOISTURE GEL 15ml（越南版乳霜）       colorkey  ...

             Loại SKU Số Qty unit/case  Số unit/combo  Dung tích(cm3)  \
0  ProductType_Single               48              0          241.50
1  ProductType_Single               48              0          241.50
2  ProductType_Single              192              0           43.75
3  ProductType_Single              192              0           43.75
4  ProductType_Single              192              0           43.75

   Mã tham khảo của Client  Đơn vị tính  Ngày hoàn tất nhập hàng  \
0       579825700767564032          pcs  2025-08-20 15:13:13.163
1       579640505284264960          pcs  2025-08-05 11:57:04.430
2           250804VX4WNHEH          pcs  2025-08-15 13:32:37.497
3          512917445913642          pcs  2025-08-15 11:30:03.797
4       579909191598114048          pcs  2025-08-30 11:05:49.883

   Giá Trị Khai Giá Mã khách hàng PO Extra Service
0               NaN           MSN             <NA>
1               NaN           MSN             <NA>
2               NaN           MSN             <NA>
3               NaN           MSN             <NA>
4               NaN           MSN             <NA>

[5 rows x 29 columns]

In [6]:
import dask
import dask.dataframe as dd
import pandas as pd
import os

path = "D:\\_workspace\\_billing\\_FEE sources\\MSN_202508.xlsx"
all_sheets = pd.read_excel(path, sheet_name=None)

dask_dataframes = {}
for sheet_name, df in all_sheets.items():
    dask_dataframes[sheet_name] = dd.from_pandas(
        df, npartitions=4
    )  # Adjust npartitions as needed

print(dask_dataframes)

:

:

In [1]:
import pandas as pd

path = "D:\\_workspace\\_billing\\_FEE sources\\MSN_202508.xlsx"
file = pd.ExcelFile(path)
print(file.sheet_names)

['ReceiveSheet', 'PrepseriveSheet', 'ReturnReceiveDeliveredSheet', 'ReturnReceiveNotDeliveredSheet', 'TransferSheet', 'TransformSheet', 'ShipSheet_1', 'ShipSheet_2', 'CODSheet', 'PackedSheet_1', 'PackedSheet_2', 'PickedSheet_1', 'PickedSheet_2', 'StorageBasedOnInventory', 'Sheet1']

In [1]:
! echo "hello"

hello

In [2]:
! ls

extraction_functional.py  extract.ipynb  extractor.py  __init__.py

In [3]:
! echo $(pwd)

/home/linhnguyen/project.de/extraction

In [2]:
offset_idx = list(range(0, 100, 20))
print(offset_idx)

[0, 20, 40, 60, 80]